services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sinatra_api_dev
      REDIS_URL: redis://redis:6379/1

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
